package com.ty.statisticsimp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table URL_ENTITY.
 */
public class UrlEntity {

    private Long id;
    /** Not-null value. */
    private String url;

    public UrlEntity() {
    }

    public UrlEntity(Long id) {
        this.id = id;
    }

    public UrlEntity(Long id, String url) {
        this.id = id;
        this.url = url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

}
